num_righe(10).
num_colonne(10).
iniziale(pos(4,2)).
finale(pos(5,3)).
occupata(pos(7,1)).
occupata(pos(7,2)).
occupata(pos(7,3)).
occupata(pos(7,4)).
occupata(pos(7,5)).
occupata(pos(2,5)).
occupata(pos(3,5)).
occupata(pos(4,5)).
occupata(pos(5,5)).
occupata(pos(6,5)).
occupata(pos(4,7)).
occupata(pos(4,8)).
occupata(pos(4,9)).
occupata(pos(4,10)).
occupata(pos(5,7)).
occupata(pos(6,7)).
occupata(pos(7,7)).
occupata(pos(8,7)).

% Celle attorno al goal: nessuna soluzione
/*occupata(pos(6,8)).
occupata(pos(6,9)).
occupata(pos(6,10)).
occupata(pos(7,8)).
occupata(pos(7,10)).
occupata(pos(8,8)).
occupata(pos(8,9)).
occupata(pos(8,10)).*/