package RetiBayesiane;


import aima.core.probability.RandomVariable;
import aima.core.probability.bayes.BayesianNetwork;
import aima.core.probability.bayes.Node;
import aima.core.probability.bayes.impl.BayesNet;
import aima.core.probability.bayes.impl.DynamicBayesNet;
import aima.core.probability.bayes.impl.FullCPTNode;
import aima.core.probability.domain.BooleanDomain;
import aima.core.probability.domain.Domain;
import aima.core.probability.util.RandVar;
import kotlin.Metadata;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

@Metadata(
        mv = {1, 1, 16},
        bv = {1, 0, 3},
        k = 1,
        d1 = {"\u0000\u001c\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0002\b\u0005\bÆ\u0002\u0018\u00002\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0002J\u0006\u0010\u0003\u001a\u00020\u0004J\u0006\u0010\u0005\u001a\u00020\u0004J\u0006\u0010\u0006\u001a\u00020\u0004J\u0006\u0010\u0007\u001a\u00020\bJ\u0006\u0010\t\u001a\u00020\u0004J\u0006\u0010\n\u001a\u00020\u0004J\u0006\u0010\u000b\u001a\u00020\u0004J\u0006\u0010\f\u001a\u00020\u0004¨\u0006\r"},
        d2 = {"LRetiBayesiane/BayesNetsFactory;", "", "()V", "getAdderNetExample", "Laima/core/probability/bayes/BayesianNetwork;", "getAlarmNet", "getChildNet", "getComplexDynamicNetworkExample", "Laima/core/probability/bayes/impl/DynamicBayesNet;", "getDigitalCircuitNetExample", "getHailfinderNet", "getPathfinderNet", "getSachsNet", "ese"}
)
public final class CustomBayesNetFactory {
    public static final CustomBayesNetFactory INSTANCE;

    public final DynamicBayesNet getComplexDynamicNetworkExample() {
        RandVar r_0 = new RandVar("R_0", (Domain)(new BooleanDomain()));
        RandVar s_0 = new RandVar("S_0", (Domain)(new BooleanDomain()));
        RandVar r_1 = new RandVar("R_1", (Domain)(new BooleanDomain()));
        RandVar s_1 = new RandVar("S_1", (Domain)(new BooleanDomain()));
        RandVar e_1 = new RandVar("E_1", (Domain)(new BooleanDomain()));
        BayesNet priorNetwork = new BayesNet(new Node[]{(Node)(new FullCPTNode((RandomVariable)r_0, new double[]{0.5D, 0.5D})), (Node)(new FullCPTNode((RandomVariable)s_0, new double[]{0.5D, 0.5D}))});
        FullCPTNode r_0_node = new FullCPTNode((RandomVariable)r_0, new double[]{0.5D, 0.5D});
        FullCPTNode s_0_node = new FullCPTNode((RandomVariable)s_0, new double[]{0.5D, 0.5D});
        FullCPTNode r_1_node = new FullCPTNode((RandomVariable)r_1, new double[]{0.1D, 0.9D, 0.15D, 0.85D, 0.7D, 0.3D, 0.8D, 0.2D}, new Node[]{(Node)r_0_node, (Node)s_0_node});
        FullCPTNode s_1_node = new FullCPTNode((RandomVariable)s_1, new double[]{0.23D, 0.77D, 0.4D, 0.6D, 0.57D, 0.43D, 0.29D, 0.71D}, new Node[]{(Node)r_0_node, (Node)s_0_node});
        new FullCPTNode((RandomVariable)e_1, new double[]{0.93D, 0.07D, 0.49D, 0.51D, 0.87D, 0.13D, 0.01D, 0.99D}, new Node[]{(Node)r_1_node, (Node)s_1_node});
        HashMap var13 = new HashMap();
        boolean var14 = false;
        boolean var15 = false;
        boolean var17 = false;
        ((Map)var13).put(r_0, r_1);
        ((Map)var13).put(s_0, s_1);
        HashSet var19 = new HashSet();
        var15 = false;
        boolean var16 = false;
        boolean var18 = false;
        var19.add(e_1);
        return new DynamicBayesNet((BayesianNetwork)priorNetwork, (Map)var13, (Set)var19, new Node[]{(Node)r_0_node, (Node)s_0_node});
    }

    public final BayesianNetwork getDigitalCircuitNetExample() {
        RandVar j = new RandVar("J", (Domain)(new BooleanDomain()));
        RandVar i = new RandVar("I", (Domain)(new BooleanDomain()));
        RandVar y = new RandVar("Y", (Domain)(new BooleanDomain()));
        RandVar x = new RandVar("X", (Domain)(new BooleanDomain()));
        RandVar o = new RandVar("O", (Domain)(new BooleanDomain()));
        FullCPTNode j_node = new FullCPTNode((RandomVariable)j, new double[]{0.5D, 0.5D});
        FullCPTNode i_node = new FullCPTNode((RandomVariable)i, new double[]{0.5D, 0.5D});
        FullCPTNode y_node = new FullCPTNode((RandomVariable)y, new double[]{0.01D, 0.99D, 0.99D, 0.01D}, new Node[]{(Node)j_node});
        FullCPTNode x_node = new FullCPTNode((RandomVariable)x, new double[]{0.95D, 0.05D, 0.05D, 0.95D, 0.05D, 0.95D, 0.05D, 0.95D}, new Node[]{(Node)j_node, (Node)i_node});
        new FullCPTNode((RandomVariable)o, new double[]{0.98D, 0.02D, 0.98D, 0.02D, 0.98D, 0.02D, 0.02D, 0.98D}, new Node[]{(Node)y_node, (Node)x_node});
        return (BayesianNetwork)(new BayesNet(new Node[]{(Node)j_node, (Node)i_node}));
    }

    public final BayesianNetwork getAdderNetExample() {
        RandVar a = new RandVar("A", (Domain)(new BooleanDomain()));
        RandVar b = new RandVar("B", (Domain)(new BooleanDomain()));
        RandVar c_in = new RandVar("C_IN", (Domain)(new BooleanDomain()));
        RandVar xor = new RandVar("XOR", (Domain)(new BooleanDomain()));
        RandVar and1 = new RandVar("AND1", (Domain)(new BooleanDomain()));
        RandVar and2 = new RandVar("AND2", (Domain)(new BooleanDomain()));
        RandVar s = new RandVar("S", (Domain)(new BooleanDomain()));
        RandVar c_out = new RandVar("C_OUT", (Domain)(new BooleanDomain()));
        FullCPTNode a_node = new FullCPTNode((RandomVariable)a, new double[]{0.5D, 0.5D});
        FullCPTNode b_node = new FullCPTNode((RandomVariable)b, new double[]{0.5D, 0.5D});
        FullCPTNode cIN_node = new FullCPTNode((RandomVariable)c_in, new double[]{0.5D, 0.5D});
        FullCPTNode xor_node = new FullCPTNode((RandomVariable)xor, new double[]{0.02D, 0.98D, 0.98D, 0.02D, 0.98D, 0.02D, 0.02D, 0.98D}, new Node[]{(Node)a_node, (Node)b_node});
        FullCPTNode and_node1 = new FullCPTNode((RandomVariable)and1, new double[]{0.95D, 0.05D, 0.05D, 0.95D, 0.05D, 0.95D, 0.05D, 0.95D}, new Node[]{(Node)xor_node, (Node)cIN_node});
        FullCPTNode and_node2 = new FullCPTNode((RandomVariable)and2, new double[]{0.95D, 0.05D, 0.05D, 0.95D, 0.05D, 0.95D, 0.05D, 0.95D}, new Node[]{(Node)a_node, (Node)b_node});
        new FullCPTNode((RandomVariable)s, new double[]{0.02D, 0.98D, 0.98D, 0.02D, 0.98D, 0.02D, 0.02D, 0.98D}, new Node[]{(Node)xor_node, (Node)cIN_node});
        new FullCPTNode((RandomVariable)c_out, new double[]{0.98D, 0.02D, 0.98D, 0.02D, 0.98D, 0.02D, 0.02D, 0.98D}, new Node[]{(Node)and_node1, (Node)and_node2});
        return (BayesianNetwork)(new BayesNet(new Node[]{(Node)a_node, (Node)b_node, (Node)cIN_node}));
    }

    public final BayesianNetwork getSachsNet() {
        RandVar akt = new RandVar("AKT", (Domain)(new BooleanDomain()));
        RandVar erk = new RandVar("ERK", (Domain)(new BooleanDomain()));
        RandVar jnk = new RandVar("JNK", (Domain)(new BooleanDomain()));
        RandVar mek = new RandVar("MEK", (Domain)(new BooleanDomain()));
        RandVar p38 = new RandVar("P38", (Domain)(new BooleanDomain()));
        RandVar pIP2 = new RandVar("PIP2", (Domain)(new BooleanDomain()));
        RandVar pIP3 = new RandVar("PIP3", (Domain)(new BooleanDomain()));
        RandVar pKA = new RandVar("PKA", (Domain)(new BooleanDomain()));
        RandVar pKC = new RandVar("PKC", (Domain)(new BooleanDomain()));
        RandVar plcg = new RandVar("PLCG", (Domain)(new BooleanDomain()));
        RandVar raf = new RandVar("RAF", (Domain)(new BooleanDomain()));
        FullCPTNode pKC_node = new FullCPTNode((RandomVariable)pKC, new double[]{0.5D, 0.5D});
        FullCPTNode plcg_node = new FullCPTNode((RandomVariable)plcg, new double[]{0.5D, 0.5D});
        FullCPTNode pKA_node = new FullCPTNode((RandomVariable)pKA, new double[]{0.76D, 0.24D, 0.015D, 0.985D}, new Node[]{(Node)pKC_node});
        FullCPTNode raf_node = new FullCPTNode((RandomVariable)raf, new double[]{0.19D, 0.81D, 0.44D, 0.56D, 0.75D, 0.25D, 0.86D, 0.14D}, new Node[]{(Node)pKA_node, (Node)pKC_node});
        FullCPTNode mek_node = new FullCPTNode((RandomVariable)mek, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.02D, 0.98D, 0.98D, 0.02D, 0.3D, 0.7D, 0.25D, 0.75D, 0.98D, 0.02D, 0.39D, 0.61D}, new Node[]{(Node)pKA_node, (Node)pKC_node, (Node)raf_node});
        FullCPTNode erk_node = new FullCPTNode((RandomVariable)erk, new double[]{0.02D, 0.98D, 0.98D, 0.02D, 0.98D, 0.02D, 0.02D, 0.98D}, new Node[]{(Node)mek_node, (Node)pKA_node});
        new FullCPTNode((RandomVariable)akt, new double[]{0.85D, 0.15D, 0.39D, 0.61D, 0.05D, 0.95D, 0.0035D, 0.9965D}, new Node[]{(Node)erk_node, (Node)pKA_node});
        new FullCPTNode((RandomVariable)jnk, new double[]{0.29D, 0.71D, 0.58D, 0.42D, 0.86D, 0.14D, 0.044D, 0.956D}, new Node[]{(Node)pKA_node, (Node)pKC_node});
        new FullCPTNode((RandomVariable)p38, new double[]{0.3D, 0.7D, 0.91D, 0.09D, 0.38D, 0.62D, 0.8D, 0.2D}, new Node[]{(Node)pKA_node, (Node)pKC_node});
        FullCPTNode pIP3_node = new FullCPTNode((RandomVariable)pIP3, new double[]{0.21D, 0.79D, 0.42D, 0.58D}, new Node[]{(Node)plcg_node});
        new FullCPTNode((RandomVariable)pIP2, new double[]{0.87D, 0.13D, 0.99D, 0.01D, 0.52D, 0.48D, 0.02D, 0.98D}, new Node[]{(Node)pIP3_node, (Node)plcg_node});
        return (BayesianNetwork)(new BayesNet(new Node[]{(Node)pKC_node, (Node)plcg_node}));
    }

    public final BayesianNetwork getChildNet() {
        RandVar birthAsphyxia = new RandVar("BIRTH_ASPHYXIA", (Domain)(new BooleanDomain()));
        RandVar hypDistrib = new RandVar("HYP_DISTRIB", (Domain)(new BooleanDomain()));
        RandVar hypoxiaInO2 = new RandVar("HYPOXIA_IN_O2", (Domain)(new BooleanDomain()));
        RandVar co2 = new RandVar("CO2", (Domain)(new BooleanDomain()));
        RandVar chestXray = new RandVar("CHEST_XRAY", (Domain)(new BooleanDomain()));
        RandVar grunting = new RandVar("GRUNTING", (Domain)(new BooleanDomain()));
        RandVar lVHreport = new RandVar("LVH_REPORT", (Domain)(new BooleanDomain()));
        RandVar lowerBodyO2 = new RandVar("LOWER_BODY_O2", (Domain)(new BooleanDomain()));
        RandVar rUQO2 = new RandVar("RUQ_O2", (Domain)(new BooleanDomain()));
        RandVar cO2Report = new RandVar("CO2_REPORT", (Domain)(new BooleanDomain()));
        RandVar xrayReport = new RandVar("XRAY_REPORT", (Domain)(new BooleanDomain()));
        RandVar disease = new RandVar("DISEASE", (Domain)(new BooleanDomain()));
        RandVar gruntingReport = new RandVar("GRUNTING_REPORT", (Domain)(new BooleanDomain()));
        RandVar age = new RandVar("AGE", (Domain)(new BooleanDomain()));
        RandVar lVH = new RandVar("LVH", (Domain)(new BooleanDomain()));
        RandVar ductFlow = new RandVar("DUCT_FLOW", (Domain)(new BooleanDomain()));
        RandVar cardiacMixing = new RandVar("CARDIAC_MIXING", (Domain)(new BooleanDomain()));
        RandVar lungParench = new RandVar("LUNG_PARENCH", (Domain)(new BooleanDomain()));
        RandVar lungFlow = new RandVar("LUNG_FLOW", (Domain)(new BooleanDomain()));
        RandVar sick = new RandVar("SICK", (Domain)(new BooleanDomain()));
        FullCPTNode birthAsphyxia_node = new FullCPTNode((RandomVariable)birthAsphyxia, new double[]{0.1D, 0.9D});
        FullCPTNode disease_node = new FullCPTNode((RandomVariable)disease, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)birthAsphyxia_node});
        FullCPTNode lVH_node = new FullCPTNode((RandomVariable)lVH, new double[]{0.9D, 0.1D, 0.05D, 0.95D}, new Node[]{(Node)disease_node});
        FullCPTNode ductFlow_node = new FullCPTNode((RandomVariable)ductFlow, new double[]{0.2D, 0.8D, 0.66D, 0.34D}, new Node[]{(Node)disease_node});
        FullCPTNode cardiacMixing_node = new FullCPTNode((RandomVariable)cardiacMixing, new double[]{0.83D, 0.17D, 0.04D, 0.96D}, new Node[]{(Node)disease_node});
        FullCPTNode lungParench_node = new FullCPTNode((RandomVariable)lungParench, new double[]{0.6D, 0.4D, 0.1D, 0.9D}, new Node[]{(Node)disease_node});
        FullCPTNode lungFlow_node = new FullCPTNode((RandomVariable)lungFlow, new double[]{0.15D, 0.85D, 0.3D, 0.7D}, new Node[]{(Node)disease_node});
        FullCPTNode sick_node = new FullCPTNode((RandomVariable)sick, new double[]{0.2D, 0.8D, 0.7D, 0.3D}, new Node[]{(Node)disease_node});
        new FullCPTNode((RandomVariable)age, new double[]{0.95D, 0.05D, 0.25D, 0.75D, 0.63D, 0.37D, 0.55D, 0.45D}, new Node[]{(Node)disease_node, (Node)sick_node});
        FullCPTNode grunting_node = new FullCPTNode((RandomVariable)grunting, new double[]{0.2D, 0.8D, 0.4D, 0.6D, 0.8D, 0.2D, 0.2D, 0.8D}, new Node[]{(Node)lungParench_node, (Node)sick_node});
        FullCPTNode co2_node = new FullCPTNode((RandomVariable)co2, new double[]{0.8D, 0.2D, 0.5D, 0.5D}, new Node[]{(Node)lungParench_node});
        FullCPTNode chestXray_node = new FullCPTNode((RandomVariable)chestXray, new double[]{0.93D, 0.07D, 0.94D, 0.06D, 0.17D, 0.83D, 0.24D, 0.76D}, new Node[]{(Node)lungParench_node, (Node)lungFlow_node});
        FullCPTNode hypDistrib_node = new FullCPTNode((RandomVariable)hypDistrib, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.95D, 0.05D, 0.5D, 0.5D}, new Node[]{(Node)ductFlow_node, (Node)cardiacMixing_node});
        FullCPTNode hypoxiaInO2_node = new FullCPTNode((RandomVariable)hypoxiaInO2, new double[]{0.93D, 0.07D, 0.9D, 0.1D, 0.7D, 0.3D, 0.35D, 0.65D}, new Node[]{(Node)cardiacMixing_node, (Node)lungParench_node});
        new FullCPTNode((RandomVariable)lVHreport, new double[]{0.2D, 0.8D, 0.05D, 0.95D}, new Node[]{(Node)lVH_node});
        new FullCPTNode((RandomVariable)lowerBodyO2, new double[]{0.4D, 0.6D, 0.5D, 0.5D, 0.1D, 0.9D, 0.6D, 0.4D}, new Node[]{(Node)hypDistrib_node, (Node)hypoxiaInO2_node});
        new FullCPTNode((RandomVariable)rUQO2, new double[]{0.1D, 0.9D, 0.3D, 0.7D}, new Node[]{(Node)hypoxiaInO2_node});
        new FullCPTNode((RandomVariable)cO2Report, new double[]{0.9D, 0.1D, 0.1D, 0.9D}, new Node[]{(Node)co2_node});
        new FullCPTNode((RandomVariable)xrayReport, new double[]{0.7D, 0.3D, 0.1D, 0.9D}, new Node[]{(Node)chestXray_node});
        new FullCPTNode((RandomVariable)gruntingReport, new double[]{0.8D, 0.2D, 0.1D, 0.9D}, new Node[]{(Node)grunting_node});
        return (BayesianNetwork)(new BayesNet(new Node[]{(Node)birthAsphyxia_node}));
    }

    public final BayesianNetwork getAlarmNet() {
        RandVar history = new RandVar("HISTORY", (Domain)(new BooleanDomain()));
        RandVar cvp = new RandVar("CVP", (Domain)(new BooleanDomain()));
        RandVar pcwp = new RandVar("PCWP", (Domain)(new BooleanDomain()));
        RandVar hypovolemia = new RandVar("HYPOVOLEMIA", (Domain)(new BooleanDomain()));
        RandVar lvedvolume = new RandVar("LVEDVOLUME", (Domain)(new BooleanDomain()));
        RandVar lvfailure = new RandVar("LVFAILURE", (Domain)(new BooleanDomain()));
        RandVar strokevolume = new RandVar("STROKEVOLUME", (Domain)(new BooleanDomain()));
        RandVar errlowoutput = new RandVar("ERRLOWOUTPUT", (Domain)(new BooleanDomain()));
        RandVar hrbp = new RandVar("HRBP", (Domain)(new BooleanDomain()));
        RandVar hrekg = new RandVar("HREKG", (Domain)(new BooleanDomain()));
        RandVar errcauter = new RandVar("ERRCAUTER", (Domain)(new BooleanDomain()));
        RandVar hrsat = new RandVar("HRSAT", (Domain)(new BooleanDomain()));
        RandVar insuffanesth = new RandVar("INSUFFANESTH", (Domain)(new BooleanDomain()));
        RandVar anaphylaxis = new RandVar("ANAPHYLAXIS", (Domain)(new BooleanDomain()));
        RandVar tpr = new RandVar("TPR", (Domain)(new BooleanDomain()));
        RandVar expco2 = new RandVar("EXPCO2", (Domain)(new BooleanDomain()));
        RandVar kinkedtube = new RandVar("KINKEDTUBE", (Domain)(new BooleanDomain()));
        RandVar minvol = new RandVar("MINVOL", (Domain)(new BooleanDomain()));
        RandVar fio2 = new RandVar("FIO2", (Domain)(new BooleanDomain()));
        RandVar pvsat = new RandVar("PVSAT", (Domain)(new BooleanDomain()));
        RandVar sao2 = new RandVar("SAO2", (Domain)(new BooleanDomain()));
        RandVar pap = new RandVar("PAP", (Domain)(new BooleanDomain()));
        RandVar pulmembolus = new RandVar("PULMEMBOLUS", (Domain)(new BooleanDomain()));
        RandVar shunt = new RandVar("SHUNT", (Domain)(new BooleanDomain()));
        RandVar intubation = new RandVar("INTUBATION", (Domain)(new BooleanDomain()));
        RandVar press = new RandVar("PRESS", (Domain)(new BooleanDomain()));
        RandVar disconnect = new RandVar("DISCONNECT", (Domain)(new BooleanDomain()));
        RandVar minvolset = new RandVar("MINVOLSET", (Domain)(new BooleanDomain()));
        RandVar ventmach = new RandVar("VENTMACH", (Domain)(new BooleanDomain()));
        RandVar venttube = new RandVar("VENTTUBE", (Domain)(new BooleanDomain()));
        RandVar ventlung = new RandVar("VENTLUNG", (Domain)(new BooleanDomain()));
        RandVar ventalv = new RandVar("VENTALV", (Domain)(new BooleanDomain()));
        RandVar artco2 = new RandVar("ARTCO2", (Domain)(new BooleanDomain()));
        RandVar catechol = new RandVar("CATECHOL", (Domain)(new BooleanDomain()));
        RandVar hr = new RandVar("HR", (Domain)(new BooleanDomain()));
        RandVar co = new RandVar("CO", (Domain)(new BooleanDomain()));
        RandVar bp = new RandVar("BP", (Domain)(new BooleanDomain()));
        FullCPTNode minvolset_node = new FullCPTNode((RandomVariable)minvolset, new double[]{0.5D, 0.5D});
        FullCPTNode hypovolemia_node = new FullCPTNode((RandomVariable)hypovolemia, new double[]{0.2D, 0.8D});
        FullCPTNode lvfailure_node = new FullCPTNode((RandomVariable)lvfailure, new double[]{0.05D, 0.95D});
        FullCPTNode errlowoutput_node = new FullCPTNode((RandomVariable)errlowoutput, new double[]{0.05D, 0.95D});
        FullCPTNode errcauter_node = new FullCPTNode((RandomVariable)errcauter, new double[]{0.1D, 0.9D});
        FullCPTNode insuffanesth_node = new FullCPTNode((RandomVariable)insuffanesth, new double[]{0.1D, 0.9D});
        FullCPTNode anaphylaxis_node = new FullCPTNode((RandomVariable)anaphylaxis, new double[]{0.01D, 0.99D});
        FullCPTNode kinkedtube_node = new FullCPTNode((RandomVariable)kinkedtube, new double[]{0.04D, 0.96D});
        FullCPTNode fio2_node = new FullCPTNode((RandomVariable)fio2, new double[]{0.05D, 0.95D});
        FullCPTNode pulmembolus_node = new FullCPTNode((RandomVariable)pulmembolus, new double[]{0.01D, 0.99D});
        FullCPTNode intubation_node = new FullCPTNode((RandomVariable)intubation, new double[]{0.92D, 0.08D});
        FullCPTNode disconnect_node = new FullCPTNode((RandomVariable)disconnect, new double[]{0.1D, 0.9D});
        new FullCPTNode((RandomVariable)catechol, new double[]{0.5D, 0.5D});
        FullCPTNode artco2_node = new FullCPTNode((RandomVariable)artco2, new double[]{0.5D, 0.5D});
        FullCPTNode ventlung_node = new FullCPTNode((RandomVariable)ventlung, new double[]{0.5D, 0.5D});
        FullCPTNode history_node = new FullCPTNode((RandomVariable)history, new double[]{0.9D, 0.1D, 0.01D, 0.99D}, new Node[]{(Node)lvfailure_node});
        FullCPTNode lvedvolume_node = new FullCPTNode((RandomVariable)lvedvolume, new double[]{0.95D, 0.05D, 0.98D, 0.02D, 0.01D, 0.99D, 0.05D, 0.95D}, new Node[]{(Node)hypovolemia_node, (Node)lvfailure_node});
        new FullCPTNode((RandomVariable)cvp, new double[]{0.85D, 0.15D, 0.29D, 0.71D}, new Node[]{(Node)lvedvolume_node});
        new FullCPTNode((RandomVariable)pcwp, new double[]{0.85D, 0.15D, 0.05D, 0.95D}, new Node[]{(Node)lvedvolume_node});
        FullCPTNode strokevolume_node = new FullCPTNode((RandomVariable)strokevolume, new double[]{0.98D, 0.02D, 0.95D, 0.05D, 0.45D, 0.55D, 0.05D, 0.95D}, new Node[]{(Node)hypovolemia_node, (Node)lvfailure_node});
        FullCPTNode hr_node = new FullCPTNode((RandomVariable)hr, new double[]{0.85D, 0.15D, 0.05D, 0.95D}, new Node[]{(Node)history_node});
        new FullCPTNode((RandomVariable)hrbp, new double[]{0.98D, 0.02D, 0.4D, 0.6D, 0.3D, 0.7D, 0.02D, 0.98D}, new Node[]{(Node)errlowoutput_node, (Node)hr_node});
        new FullCPTNode((RandomVariable)hrekg, new double[]{0.34D, 0.66D, 0.34D, 0.66D, 0.98D, 0.02D, 0.01D, 0.99D}, new Node[]{(Node)errcauter_node, (Node)hr_node});
        new FullCPTNode((RandomVariable)hrsat, new double[]{0.34D, 0.66D, 0.34D, 0.66D, 0.98D, 0.02D, 0.01D, 0.99D}, new Node[]{(Node)errcauter_node, (Node)hr_node});
        FullCPTNode tpr_node = new FullCPTNode((RandomVariable)tpr, new double[]{0.98D, 0.02D, 0.3D, 0.7D}, new Node[]{(Node)anaphylaxis_node});
        new FullCPTNode((RandomVariable)expco2, new double[]{0.97D, 0.03D, 0.98D, 0.02D, 0.02D, 0.98D, 0.01D, 0.99D}, new Node[]{(Node)artco2_node, (Node)ventlung_node});
        FullCPTNode ventmach_node = new FullCPTNode((RandomVariable)ventmach, new double[]{0.98D, 0.02D, 0.06D, 0.94D}, new Node[]{(Node)minvolset_node});
        FullCPTNode venttube_node = new FullCPTNode((RandomVariable)venttube, new double[]{0.98D, 0.02D, 0.95D, 0.05D, 0.9D, 0.1D, 0.69D, 0.31D}, new Node[]{(Node)disconnect_node, (Node)ventmach_node});
        ventlung_node = new FullCPTNode((RandomVariable)ventlung, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.02D, 0.98D, 0.98D, 0.02D, 0.3D, 0.7D, 0.25D, 0.75D, 0.98D, 0.02D, 0.39D, 0.61D}, new Node[]{(Node)intubation_node, (Node)kinkedtube_node, (Node)venttube_node});
        new FullCPTNode((RandomVariable)minvol, new double[]{0.97D, 0.03D, 0.98D, 0.02D, 0.02D, 0.98D, 0.01D, 0.99D}, new Node[]{(Node)intubation_node, (Node)ventlung_node});
        FullCPTNode ventalv_node = new FullCPTNode((RandomVariable)ventalv, new double[]{0.97D, 0.03D, 0.98D, 0.02D, 0.02D, 0.98D, 0.12D, 0.88D}, new Node[]{(Node)intubation_node, (Node)ventlung_node});
        FullCPTNode pvsat_node = new FullCPTNode((RandomVariable)pvsat, new double[]{1.0D, 0.0D, 0.99D, 0.01D, 1.0D, 0.0D, 0.02D, 0.98D}, new Node[]{(Node)fio2_node, (Node)ventalv_node});
        FullCPTNode shunt_node = new FullCPTNode((RandomVariable)shunt, new double[]{0.1D, 0.9D, 0.1D, 0.9D, 0.95D, 0.05D, 0.05D, 0.95D}, new Node[]{(Node)intubation_node, (Node)pulmembolus_node});
        FullCPTNode sao2_node = new FullCPTNode((RandomVariable)sao2, new double[]{0.98D, 0.02D, 0.95D, 0.05D, 0.9D, 0.1D, 0.69D, 0.31D}, new Node[]{(Node)pvsat_node, (Node)shunt_node});
        new FullCPTNode((RandomVariable)pap, new double[]{0.2D, 0.8D, 0.05D, 0.95D}, new Node[]{(Node)pulmembolus_node});
        new FullCPTNode((RandomVariable)press, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.02D, 0.98D, 0.98D, 0.02D, 0.3D, 0.7D, 0.25D, 0.75D, 0.98D, 0.02D, 0.39D, 0.61D}, new Node[]{(Node)intubation_node, (Node)kinkedtube_node, (Node)venttube_node});
        artco2_node = new FullCPTNode((RandomVariable)artco2, new double[]{0.02D, 0.98D, 0.9D, 0.1D}, new Node[]{(Node)ventalv_node});
        new FullCPTNode((RandomVariable)catechol, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.02D, 0.98D, 0.98D, 0.02D, 0.3D, 0.7D, 0.25D, 0.75D, 0.98D, 0.02D, 0.39D, 0.61D, 0.55D, 0.45D, 0.17D, 0.83D, 0.02D, 0.98D, 0.98D, 0.02D, 0.44D, 0.56D, 0.25D, 0.75D, 0.98D, 0.02D, 0.19D, 0.81D}, new Node[]{(Node)artco2_node, (Node)insuffanesth_node, (Node)sao2_node, (Node)tpr_node});
        FullCPTNode co_node = new FullCPTNode((RandomVariable)co, new double[]{0.98D, 0.02D, 0.95D, 0.05D, 0.31D, 0.69D, 0.02D, 0.98D}, new Node[]{(Node)hr_node, (Node)strokevolume_node});
        new FullCPTNode((RandomVariable)bp, new double[]{0.98D, 0.02D, 0.98D, 0.02D, 0.15D, 0.85D, 0.45D, 0.55D}, new Node[]{(Node)co_node, (Node)tpr_node});
        return (BayesianNetwork)(new BayesNet(new Node[]{(Node)hypovolemia_node, (Node)lvfailure_node, (Node)errlowoutput_node, (Node)errcauter_node, (Node)insuffanesth_node, (Node)anaphylaxis_node, (Node)kinkedtube_node, (Node)fio2_node, (Node)pulmembolus_node, (Node)intubation_node, (Node)disconnect_node, (Node)minvolset_node}));
    }

    public final BayesianNetwork getHailfinderNet() {
        RandVar n0_7muVerMo = new RandVar("N0_7MU_VERMO", (Domain)(new BooleanDomain()));
        RandVar subjVertMo = new RandVar("SUBJ:VERTMO", (Domain)(new BooleanDomain()));
        RandVar qGVertMotion = new RandVar("QG_VERTMOTION", (Domain)(new BooleanDomain()));
        RandVar combVerMo = new RandVar("COMB_VERMO", (Domain)(new BooleanDomain()));
        RandVar areaMeso_ALS = new RandVar("AREAMESO_ALS", (Domain)(new BooleanDomain()));
        RandVar satContMoist = new RandVar("SATCONTMOIST", (Domain)(new BooleanDomain()));
        RandVar raoContMoist = new RandVar("RAOCONTMOIST", (Domain)(new BooleanDomain()));
        RandVar combMoisture = new RandVar("COMB_MOISTURE", (Domain)(new BooleanDomain()));
        RandVar areaMoDryAir = new RandVar("AREAMO_DRYAIR", (Domain)(new BooleanDomain()));
        RandVar vISCloudCov = new RandVar("VIS_CLOUDCOV", (Domain)(new BooleanDomain()));
        RandVar iRCloudCover = new RandVar("IR_CLOUDCOV", (Domain)(new BooleanDomain()));
        RandVar combClouds = new RandVar("COMB_CLOUDS", (Domain)(new BooleanDomain()));
        RandVar cldShadeOth = new RandVar("CLD_SHADE_OTH", (Domain)(new BooleanDomain()));
        RandVar aMInstabMt = new RandVar("AN_INSTAB_MT", (Domain)(new BooleanDomain()));
        RandVar insInMt = new RandVar("INS_IN_MT", (Domain)(new BooleanDomain()));
        RandVar wndHodograph = new RandVar("WND_HODOGRAPH", (Domain)(new BooleanDomain()));
        RandVar outflowFrMt = new RandVar("OUTFLOW_FRMT", (Domain)(new BooleanDomain()));
        RandVar morningBound = new RandVar("MORNING_BOUND", (Domain)(new BooleanDomain()));
        RandVar boundaries = new RandVar("BOUNDARIES", (Domain)(new BooleanDomain()));
        RandVar cldShadeConv = new RandVar("CLD_SHADE_CONV", (Domain)(new BooleanDomain()));
        RandVar compPlFcst = new RandVar("COMPL_FCST", (Domain)(new BooleanDomain()));
        RandVar capChange = new RandVar("CAP_CHANGE", (Domain)(new BooleanDomain()));
        RandVar loLevMoistAd = new RandVar("LOLEV_MOIST_AD", (Domain)(new BooleanDomain()));
        RandVar insChange = new RandVar("INS_CHANGE", (Domain)(new BooleanDomain()));
        RandVar mountainFcst = new RandVar("MOUNTAIN_FCST", (Domain)(new BooleanDomain()));
        RandVar date = new RandVar("DATE", (Domain)(new BooleanDomain()));
        RandVar scenario = new RandVar("SCENARIO", (Domain)(new BooleanDomain()));
        RandVar scenRelAMCIN = new RandVar("SCEN_REL_AMCIN", (Domain)(new BooleanDomain()));
        RandVar morningCIN = new RandVar("MORNING_CIN", (Domain)(new BooleanDomain()));
        RandVar aMCINInScen = new RandVar("AMCIN_IN_SCEN", (Domain)(new BooleanDomain()));
        new RandVar("CAP_IN_SCEN", (Domain)(new BooleanDomain()));
        RandVar scenRelAMIns = new RandVar("SCEN_REL_AMINS", (Domain)(new BooleanDomain()));
        RandVar lIfr12ZDENSd = new RandVar("LIFR23ZDENSD", (Domain)(new BooleanDomain()));
        RandVar aMDewptCalPl = new RandVar("AMDEWPTCALPL", (Domain)(new BooleanDomain()));
        RandVar aMInsWliScen = new RandVar("AM_INS_WLISCEN", (Domain)(new BooleanDomain()));
        RandVar insSclInScen = new RandVar("INS_SCL_INSCEN", (Domain)(new BooleanDomain()));
        RandVar scenRel3_4 = new RandVar("SCEN_REL3_4", (Domain)(new BooleanDomain()));
        RandVar latestCIN = new RandVar("LATEST_CIN", (Domain)(new BooleanDomain()));
        RandVar lLIW = new RandVar("LLIW", (Domain)(new BooleanDomain()));
        RandVar curPropConv = new RandVar("CUR_PROP_CONV", (Domain)(new BooleanDomain()));
        RandVar scnRelPlFcst = new RandVar("SCN_REL_PLFCST", (Domain)(new BooleanDomain()));
        RandVar plainsFcst = new RandVar("PLAINS_FCST", (Domain)(new BooleanDomain()));
        RandVar n34StarFcst = new RandVar("N34_STAR_FCST", (Domain)(new BooleanDomain()));
        RandVar r5Fcst = new RandVar("R5_FCST", (Domain)(new BooleanDomain()));
        RandVar dewpoints = new RandVar("DEW_POINTS", (Domain)(new BooleanDomain()));
        RandVar lowLLapse = new RandVar("LOWL_LAPSE", (Domain)(new BooleanDomain()));
        RandVar meanRH = new RandVar("MEAN_RH", (Domain)(new BooleanDomain()));
        RandVar midLLapse = new RandVar("MID_LAPSE", (Domain)(new BooleanDomain()));
        RandVar mvmtFeatures = new RandVar("MVMT_FEATURES", (Domain)(new BooleanDomain()));
        RandVar rHRatio = new RandVar("RH_RATIO", (Domain)(new BooleanDomain()));
        RandVar sfcWndShfDis = new RandVar("SFC_WND_SHF_DIS", (Domain)(new BooleanDomain()));
        RandVar synForcng = new RandVar("SYN_FORCNG", (Domain)(new BooleanDomain()));
        RandVar tempDis = new RandVar("TEMP_DIS", (Domain)(new BooleanDomain()));
        RandVar windAloft = new RandVar("WIND_A_LOFT", (Domain)(new BooleanDomain()));
        RandVar windFieldMt = new RandVar("WIND_FIELD_MT", (Domain)(new BooleanDomain()));
        RandVar windFieldPln = new RandVar("WIND_FIELD_PIN", (Domain)(new BooleanDomain()));
        FullCPTNode n0_7muVerMo_node = new FullCPTNode((RandomVariable)n0_7muVerMo, new double[]{0.5D, 0.5D});
        FullCPTNode subjVertMo_node = new FullCPTNode((RandomVariable)subjVertMo, new double[]{0.3D, 0.7D});
        FullCPTNode qGVertMotion_node = new FullCPTNode((RandomVariable)qGVertMotion, new double[]{0.3D, 0.7D});
        FullCPTNode satContMoist_node = new FullCPTNode((RandomVariable)satContMoist, new double[]{0.35D, 0.65D});
        FullCPTNode raoContMoist_node = new FullCPTNode((RandomVariable)raoContMoist, new double[]{0.35D, 0.65D});
        FullCPTNode vISCloudCov_node = new FullCPTNode((RandomVariable)vISCloudCov, new double[]{0.6D, 0.4D});
        FullCPTNode iRCloudCover_node = new FullCPTNode((RandomVariable)iRCloudCover, new double[]{0.15D, 0.85D});
        FullCPTNode aMInstabMt_node = new FullCPTNode((RandomVariable)aMInstabMt, new double[]{0.33D, 0.67D});
        FullCPTNode wndHodograph_node = new FullCPTNode((RandomVariable)wndHodograph, new double[]{0.5D, 0.5D});
        FullCPTNode morningBound_node = new FullCPTNode((RandomVariable)morningBound, new double[]{0.5D, 0.5D});
        FullCPTNode loLevMoistAd_node = new FullCPTNode((RandomVariable)loLevMoistAd, new double[]{0.4D, 0.6D});
        FullCPTNode date_node = new FullCPTNode((RandomVariable)date, new double[]{0.5D, 0.5D});
        FullCPTNode morningCIN_node = new FullCPTNode((RandomVariable)morningCIN, new double[]{0.72D, 0.28D});
        FullCPTNode lIfr12ZDENSd_node = new FullCPTNode((RandomVariable)lIfr12ZDENSd, new double[]{0.62D, 0.38D});
        FullCPTNode aMDewptCalPl_node = new FullCPTNode((RandomVariable)aMDewptCalPl, new double[]{0.55D, 0.45D});
        FullCPTNode latestCIN_node = new FullCPTNode((RandomVariable)latestCIN, new double[]{0.8D, 0.2D});
        FullCPTNode lLIW_node = new FullCPTNode((RandomVariable)lLIW, new double[]{0.44D, 0.56D});
        FullCPTNode combVerMo_node = new FullCPTNode((RandomVariable)combVerMo, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.02D, 0.98D, 0.98D, 0.02D, 0.3D, 0.7D, 0.55D, 0.45D, 0.98D, 0.02D, 0.39D, 0.61D}, new Node[]{(Node)n0_7muVerMo_node, (Node)subjVertMo_node, (Node)qGVertMotion_node});
        FullCPTNode areaMeso_ALS_node = new FullCPTNode((RandomVariable)areaMeso_ALS, new double[]{0.95D, 0.05D, 0.05D, 0.95D}, new Node[]{(Node)combVerMo_node});
        FullCPTNode combMoisture_node = new FullCPTNode((RandomVariable)combMoisture, new double[]{0.9D, 0.1D, 0.55D, 0.45D, 0.45D, 0.55D, 0.25D, 0.75D}, new Node[]{(Node)satContMoist_node, (Node)raoContMoist_node});
        FullCPTNode areaMoDryAir_node = new FullCPTNode((RandomVariable)areaMoDryAir, new double[]{0.99D, 0.01D, 0.7D, 0.3D, 0.4D, 0.6D, 0.02D, 0.98D}, new Node[]{(Node)areaMeso_ALS_node, (Node)combMoisture_node});
        FullCPTNode combClouds_node = new FullCPTNode((RandomVariable)combClouds, new double[]{0.95D, 0.05D, 0.58D, 0.42D, 0.3D, 0.7D, 0.05D, 0.95D}, new Node[]{(Node)vISCloudCov_node, (Node)iRCloudCover_node});
        FullCPTNode cldShadeOth_node = new FullCPTNode((RandomVariable)cldShadeOth, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.02D, 0.98D, 0.98D, 0.02D, 0.4D, 0.6D, 0.25D, 0.75D, 0.98D, 0.02D, 0.39D, 0.61D}, new Node[]{(Node)areaMoDryAir_node, (Node)areaMeso_ALS_node, (Node)combClouds_node});
        FullCPTNode insInMt_node = new FullCPTNode((RandomVariable)insInMt, new double[]{0.99D, 0.01D, 0.7D, 0.3D, 0.4D, 0.6D, 0.02D, 0.98D}, new Node[]{(Node)cldShadeOth_node, (Node)aMInstabMt_node});
        FullCPTNode outflowFrMt_node = new FullCPTNode((RandomVariable)outflowFrMt, new double[]{0.9D, 0.1D, 0.5D, 0.5D, 0.35D, 0.65D, 0.08D, 0.92D}, new Node[]{(Node)insInMt_node, (Node)wndHodograph_node});
        FullCPTNode boundaries_node = new FullCPTNode((RandomVariable)boundaries, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.02D, 0.98D, 0.98D, 0.02D, 0.3D, 0.7D, 0.31D, 0.69D, 0.98D, 0.02D, 0.39D, 0.61D}, new Node[]{(Node)outflowFrMt_node, (Node)wndHodograph_node, (Node)morningBound_node});
        FullCPTNode cldShadeConv_node = new FullCPTNode((RandomVariable)cldShadeConv, new double[]{0.9D, 0.1D, 0.5D, 0.5D, 0.35D, 0.65D, 0.08D, 0.92D}, new Node[]{(Node)insInMt_node, (Node)wndHodograph_node});
        FullCPTNode compPlFcst_node = new FullCPTNode((RandomVariable)compPlFcst, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.02D, 0.98D, 0.98D, 0.02D, 0.3D, 0.7D, 0.25D, 0.75D, 0.98D, 0.02D, 0.39D, 0.61D, 0.55D, 0.45D, 0.17D, 0.83D, 0.02D, 0.98D, 0.98D, 0.02D, 0.44D, 0.56D, 0.25D, 0.75D, 0.98D, 0.02D, 0.19D, 0.81D}, new Node[]{(Node)boundaries_node, (Node)cldShadeConv_node, (Node)areaMeso_ALS_node, (Node)cldShadeOth_node});
        FullCPTNode capChange_node = new FullCPTNode((RandomVariable)capChange, new double[]{0.9D, 0.1D, 0.19D, 0.81D}, new Node[]{(Node)compPlFcst_node});
        new FullCPTNode((RandomVariable)insChange, new double[]{0.9D, 0.1D, 0.44D, 0.56D, 0.35D, 0.65D, 0.08D, 0.92D}, new Node[]{(Node)loLevMoistAd_node, (Node)compPlFcst_node});
        FullCPTNode mountainFcst_node = new FullCPTNode((RandomVariable)mountainFcst, new double[]{0.9D, 0.1D, 0.18D, 0.82D}, new Node[]{(Node)insInMt_node});
        FullCPTNode scenario_node = new FullCPTNode((RandomVariable)scenario, new double[]{0.9D, 0.1D, 0.35D, 0.65D}, new Node[]{(Node)date_node});
        FullCPTNode scenRelAMCIN_node = new FullCPTNode((RandomVariable)scenRelAMCIN, new double[]{0.9D, 0.1D, 0.17D, 0.83D}, new Node[]{(Node)scenario_node});
        FullCPTNode aMCINInScen_node = new FullCPTNode((RandomVariable)aMCINInScen, new double[]{0.9D, 0.1D, 0.5D, 0.5D, 0.35D, 0.65D, 0.08D, 0.92D}, new Node[]{(Node)scenRelAMCIN_node, (Node)morningCIN_node});
        FullCPTNode capInScen_node = new FullCPTNode((RandomVariable)insChange, new double[]{0.9D, 0.1D, 0.5D, 0.5D, 0.35D, 0.65D, 0.08D, 0.92D}, new Node[]{(Node)aMCINInScen_node, (Node)capChange_node});
        FullCPTNode scenRelAMIns_node = new FullCPTNode((RandomVariable)scenRelAMIns, new double[]{0.9D, 0.1D, 0.39D, 0.61D}, new Node[]{(Node)scenario_node});
        FullCPTNode aMInsWliScen_node = new FullCPTNode((RandomVariable)aMInsWliScen, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.02D, 0.98D, 0.98D, 0.02D, 0.3D, 0.7D, 0.25D, 0.75D, 0.98D, 0.02D, 0.39D, 0.61D}, new Node[]{(Node)scenRelAMIns_node, (Node)lIfr12ZDENSd_node, (Node)aMDewptCalPl_node});
        FullCPTNode insSclInScen_node = new FullCPTNode((RandomVariable)insSclInScen, new double[]{0.9D, 0.1D, 0.08D, 0.92D}, new Node[]{(Node)aMInsWliScen_node});
        FullCPTNode scenRel3_4_node = new FullCPTNode((RandomVariable)scenRel3_4, new double[]{0.9D, 0.1D, 0.08D, 0.92D}, new Node[]{(Node)scenario_node});
        FullCPTNode curPropConv_node = new FullCPTNode((RandomVariable)curPropConv, new double[]{0.9D, 0.1D, 0.5D, 0.5D, 0.35D, 0.65D, 0.08D, 0.92D}, new Node[]{(Node)latestCIN_node, (Node)lLIW_node});
        FullCPTNode scnRelPlFcst_node = new FullCPTNode((RandomVariable)scnRelPlFcst, new double[]{0.9D, 0.1D, 0.5D, 0.5D}, new Node[]{(Node)scenario_node});
        FullCPTNode plainsFcst_node = new FullCPTNode((RandomVariable)plainsFcst, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.02D, 0.98D, 0.98D, 0.02D, 0.3D, 0.7D, 0.25D, 0.75D, 0.98D, 0.02D, 0.39D, 0.61D, 0.55D, 0.45D, 0.17D, 0.83D, 0.02D, 0.98D, 0.98D, 0.02D, 0.44D, 0.56D, 0.25D, 0.75D, 0.98D, 0.02D, 0.19D, 0.81D}, new Node[]{(Node)curPropConv_node, (Node)insSclInScen_node, (Node)capInScen_node, (Node)scnRelPlFcst_node});
        FullCPTNode n34StarFcst_node = new FullCPTNode((RandomVariable)n34StarFcst, new double[]{0.9D, 0.1D, 0.39D, 0.61D, 0.35D, 0.65D, 0.08D, 0.92D}, new Node[]{(Node)scenRel3_4_node, (Node)plainsFcst_node});
        new FullCPTNode((RandomVariable)r5Fcst, new double[]{0.9D, 0.1D, 0.5D, 0.5D, 0.35D, 0.65D, 0.08D, 0.92D}, new Node[]{(Node)mountainFcst_node, (Node)n34StarFcst_node});
        new FullCPTNode((RandomVariable)dewpoints, new double[]{0.9D, 0.1D, 0.25D, 0.75D}, new Node[]{(Node)scenario_node});
        new FullCPTNode((RandomVariable)lowLLapse, new double[]{0.9D, 0.1D, 0.17D, 0.83D}, new Node[]{(Node)scenario_node});
        new FullCPTNode((RandomVariable)meanRH, new double[]{0.9D, 0.1D, 0.35D, 0.65D}, new Node[]{(Node)scenario_node});
        new FullCPTNode((RandomVariable)midLLapse, new double[]{0.9D, 0.1D, 0.25D, 0.75D}, new Node[]{(Node)scenario_node});
        new FullCPTNode((RandomVariable)mvmtFeatures, new double[]{0.9D, 0.1D, 0.15D, 0.85D}, new Node[]{(Node)scenario_node});
        new FullCPTNode((RandomVariable)rHRatio, new double[]{0.9D, 0.1D, 0.35D, 0.65D}, new Node[]{(Node)scenario_node});
        new FullCPTNode((RandomVariable)sfcWndShfDis, new double[]{0.9D, 0.1D, 0.55D, 0.45D}, new Node[]{(Node)scenario_node});
        new FullCPTNode((RandomVariable)synForcng, new double[]{0.9D, 0.1D, 0.65D, 0.35D}, new Node[]{(Node)scenario_node});
        new FullCPTNode((RandomVariable)tempDis, new double[]{0.9D, 0.1D, 0.5D, 0.5D}, new Node[]{(Node)scenario_node});
        new FullCPTNode((RandomVariable)windAloft, new double[]{0.9D, 0.1D, 0.15D, 0.85D}, new Node[]{(Node)scenario_node});
        new FullCPTNode((RandomVariable)windFieldMt, new double[]{0.9D, 0.1D, 0.5D, 0.5D}, new Node[]{(Node)scenario_node});
        new FullCPTNode((RandomVariable)windFieldPln, new double[]{0.9D, 0.1D, 0.15D, 0.85D}, new Node[]{(Node)scenario_node});
        return (BayesianNetwork)(new BayesNet(new Node[]{(Node)n0_7muVerMo_node, (Node)subjVertMo_node, (Node)qGVertMotion_node, (Node)satContMoist_node, (Node)raoContMoist_node, (Node)vISCloudCov_node, (Node)iRCloudCover_node, (Node)aMInstabMt_node, (Node)wndHodograph_node, (Node)morningBound_node, (Node)loLevMoistAd_node, (Node)date_node, (Node)morningCIN_node, (Node)lIfr12ZDENSd_node, (Node)aMDewptCalPl_node, (Node)latestCIN_node, (Node)lLIW_node}));
    }

    public final BayesianNetwork getPathfinderNet() {
        RandVar fault = new RandVar("FAULT", (Domain)(new BooleanDomain()));
        RandVar f1 = new RandVar("F1", (Domain)(new BooleanDomain()));
        RandVar f97 = new RandVar("F97", (Domain)(new BooleanDomain()));
        RandVar f2 = new RandVar("F2", (Domain)(new BooleanDomain()));
        RandVar f78 = new RandVar("F78", (Domain)(new BooleanDomain()));
        RandVar f3 = new RandVar("F3", (Domain)(new BooleanDomain()));
        RandVar f4 = new RandVar("F4", (Domain)(new BooleanDomain()));
        RandVar f5 = new RandVar("F5", (Domain)(new BooleanDomain()));
        RandVar f53 = new RandVar("F53", (Domain)(new BooleanDomain()));
        RandVar f6 = new RandVar("F6", (Domain)(new BooleanDomain()));
        RandVar f7 = new RandVar("F7", (Domain)(new BooleanDomain()));
        RandVar f56 = new RandVar("F56", (Domain)(new BooleanDomain()));
        RandVar f8 = new RandVar("F8", (Domain)(new BooleanDomain()));
        RandVar f9 = new RandVar("F9", (Domain)(new BooleanDomain()));
        RandVar f10 = new RandVar("F10", (Domain)(new BooleanDomain()));
        RandVar f55 = new RandVar("F55", (Domain)(new BooleanDomain()));
        RandVar f52 = new RandVar("F52", (Domain)(new BooleanDomain()));
        RandVar f11 = new RandVar("F11", (Domain)(new BooleanDomain()));
        RandVar f12 = new RandVar("F12", (Domain)(new BooleanDomain()));
        RandVar f13 = new RandVar("F13", (Domain)(new BooleanDomain()));
        RandVar f14 = new RandVar("F14", (Domain)(new BooleanDomain()));
        RandVar f15 = new RandVar("F15", (Domain)(new BooleanDomain()));
        RandVar f16 = new RandVar("F16", (Domain)(new BooleanDomain()));
        RandVar f17 = new RandVar("F17", (Domain)(new BooleanDomain()));
        RandVar f18 = new RandVar("F18", (Domain)(new BooleanDomain()));
        RandVar f19 = new RandVar("F19", (Domain)(new BooleanDomain()));
        RandVar f41 = new RandVar("F41", (Domain)(new BooleanDomain()));
        RandVar f44 = new RandVar("F44", (Domain)(new BooleanDomain()));
        RandVar f20 = new RandVar("F20", (Domain)(new BooleanDomain()));
        RandVar f90 = new RandVar("F90", (Domain)(new BooleanDomain()));
        RandVar f21 = new RandVar("F21", (Domain)(new BooleanDomain()));
        RandVar f22 = new RandVar("F22", (Domain)(new BooleanDomain()));
        RandVar f23 = new RandVar("F23", (Domain)(new BooleanDomain()));
        RandVar f24 = new RandVar("F24", (Domain)(new BooleanDomain()));
        RandVar f25 = new RandVar("F25", (Domain)(new BooleanDomain()));
        RandVar f26 = new RandVar("F26", (Domain)(new BooleanDomain()));
        RandVar f27 = new RandVar("F27", (Domain)(new BooleanDomain()));
        RandVar f28 = new RandVar("F28", (Domain)(new BooleanDomain()));
        RandVar f92 = new RandVar("F92", (Domain)(new BooleanDomain()));
        RandVar f29 = new RandVar("F29", (Domain)(new BooleanDomain()));
        RandVar f98 = new RandVar("F98", (Domain)(new BooleanDomain()));
        RandVar f30 = new RandVar("F30", (Domain)(new BooleanDomain()));
        RandVar f31 = new RandVar("F31", (Domain)(new BooleanDomain()));
        RandVar f32 = new RandVar("F32", (Domain)(new BooleanDomain()));
        RandVar f33 = new RandVar("F33", (Domain)(new BooleanDomain()));
        RandVar f34 = new RandVar("F34", (Domain)(new BooleanDomain()));
        RandVar f35 = new RandVar("F35", (Domain)(new BooleanDomain()));
        RandVar f36 = new RandVar("F36", (Domain)(new BooleanDomain()));
        RandVar f37 = new RandVar("F37", (Domain)(new BooleanDomain()));
        RandVar f84 = new RandVar("F84", (Domain)(new BooleanDomain()));
        RandVar f96 = new RandVar("F96", (Domain)(new BooleanDomain()));
        RandVar f38 = new RandVar("F38", (Domain)(new BooleanDomain()));
        RandVar f39 = new RandVar("F39", (Domain)(new BooleanDomain()));
        RandVar f40 = new RandVar("F40", (Domain)(new BooleanDomain()));
        RandVar f42 = new RandVar("F42", (Domain)(new BooleanDomain()));
        RandVar f43 = new RandVar("F43", (Domain)(new BooleanDomain()));
        RandVar f45 = new RandVar("F45", (Domain)(new BooleanDomain()));
        RandVar f46 = new RandVar("F46", (Domain)(new BooleanDomain()));
        new RandVar("F47", (Domain)(new BooleanDomain()));
        RandVar f85 = new RandVar("F85", (Domain)(new BooleanDomain()));
        RandVar f48 = new RandVar("F48", (Domain)(new BooleanDomain()));
        RandVar f49 = new RandVar("F49", (Domain)(new BooleanDomain()));
        RandVar f50 = new RandVar("F50", (Domain)(new BooleanDomain()));
        RandVar f51 = new RandVar("F51", (Domain)(new BooleanDomain()));
        RandVar f83 = new RandVar("F83", (Domain)(new BooleanDomain()));
        RandVar f54 = new RandVar("F54", (Domain)(new BooleanDomain()));
        RandVar f57 = new RandVar("F57", (Domain)(new BooleanDomain()));
        RandVar f58 = new RandVar("F58", (Domain)(new BooleanDomain()));
        RandVar f59 = new RandVar("F59", (Domain)(new BooleanDomain()));
        RandVar f60 = new RandVar("F60", (Domain)(new BooleanDomain()));
        new RandVar("F61", (Domain)(new BooleanDomain()));
        RandVar f62 = new RandVar("F62", (Domain)(new BooleanDomain()));
        RandVar f63 = new RandVar("F63", (Domain)(new BooleanDomain()));
        RandVar f64 = new RandVar("F64", (Domain)(new BooleanDomain()));
        RandVar f65 = new RandVar("F65", (Domain)(new BooleanDomain()));
        RandVar f66 = new RandVar("F66", (Domain)(new BooleanDomain()));
        RandVar f67 = new RandVar("F67", (Domain)(new BooleanDomain()));
        RandVar f68 = new RandVar("F68", (Domain)(new BooleanDomain()));
        RandVar f69 = new RandVar("F69", (Domain)(new BooleanDomain()));
        RandVar f72 = new RandVar("F72", (Domain)(new BooleanDomain()));
        RandVar f86 = new RandVar("F86", (Domain)(new BooleanDomain()));
        RandVar f70 = new RandVar("F70", (Domain)(new BooleanDomain()));
        RandVar f71 = new RandVar("F71", (Domain)(new BooleanDomain()));
        RandVar f73 = new RandVar("F73", (Domain)(new BooleanDomain()));
        RandVar f74 = new RandVar("F74", (Domain)(new BooleanDomain()));
        RandVar f75 = new RandVar("F75", (Domain)(new BooleanDomain()));
        RandVar f76 = new RandVar("F76", (Domain)(new BooleanDomain()));
        RandVar f77 = new RandVar("F77", (Domain)(new BooleanDomain()));
        RandVar f79 = new RandVar("F79", (Domain)(new BooleanDomain()));
        RandVar f80 = new RandVar("F80", (Domain)(new BooleanDomain()));
        new RandVar("F81", (Domain)(new BooleanDomain()));
        RandVar f82 = new RandVar("F82", (Domain)(new BooleanDomain()));
        RandVar f87 = new RandVar("F87", (Domain)(new BooleanDomain()));
        RandVar f88 = new RandVar("F88", (Domain)(new BooleanDomain()));
        RandVar f89 = new RandVar("F89", (Domain)(new BooleanDomain()));
        RandVar f91 = new RandVar("F91", (Domain)(new BooleanDomain()));
        RandVar f93 = new RandVar("F93", (Domain)(new BooleanDomain()));
        RandVar f94 = new RandVar("F94", (Domain)(new BooleanDomain()));
        RandVar f95 = new RandVar("F95", (Domain)(new BooleanDomain()));
        RandVar f99 = new RandVar("F99", (Domain)(new BooleanDomain()));
        RandVar f100 = new RandVar("F100", (Domain)(new BooleanDomain()));
        RandVar f105 = new RandVar("F105", (Domain)(new BooleanDomain()));
        RandVar f101 = new RandVar("F101", (Domain)(new BooleanDomain()));
        RandVar f102 = new RandVar("F102", (Domain)(new BooleanDomain()));
        RandVar f103 = new RandVar("F103", (Domain)(new BooleanDomain()));
        RandVar f104 = new RandVar("F104", (Domain)(new BooleanDomain()));
        RandVar f106 = new RandVar("F106", (Domain)(new BooleanDomain()));
        RandVar f107 = new RandVar("F107", (Domain)(new BooleanDomain()));
        RandVar f108 = new RandVar("F108", (Domain)(new BooleanDomain()));
        FullCPTNode fault_node = new FullCPTNode((RandomVariable)fault, new double[]{0.5D, 0.5D});
        new FullCPTNode((RandomVariable)f1, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f97, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f2_node = new FullCPTNode((RandomVariable)f2, new double[]{0.95D, 0.05D, 0.5D, 0.5D}, new Node[]{(Node)fault_node});
        FullCPTNode f78_node = new FullCPTNode((RandomVariable)f78, new double[]{0.95D, 0.05D, 0.5D, 0.5D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f3, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f78_node});
        FullCPTNode f4_node = new FullCPTNode((RandomVariable)f4, new double[]{0.95D, 0.05D, 0.5D, 0.5D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f5, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f2_node});
        FullCPTNode f53_node = new FullCPTNode((RandomVariable)f53, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f6, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f53_node});
        new FullCPTNode((RandomVariable)f7, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f56_node = new FullCPTNode((RandomVariable)f56, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f8_node = new FullCPTNode((RandomVariable)f8, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f53_node, (Node)f56_node});
        new FullCPTNode((RandomVariable)f9, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f10, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f55_node = new FullCPTNode((RandomVariable)f55, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f52_node = new FullCPTNode((RandomVariable)f52, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f55_node});
        new FullCPTNode((RandomVariable)f11, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f52_node});
        new FullCPTNode((RandomVariable)f12, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f13, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f8_node});
        new FullCPTNode((RandomVariable)f14, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f15_node = new FullCPTNode((RandomVariable)f15, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f16, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f15_node});
        FullCPTNode f17_node = new FullCPTNode((RandomVariable)f17, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f18, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f17_node});
        new FullCPTNode((RandomVariable)f19, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f41_node = new FullCPTNode((RandomVariable)f41, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f44_node = new FullCPTNode((RandomVariable)f44, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f20_node = new FullCPTNode((RandomVariable)f20, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f41_node, (Node)f44_node});
        FullCPTNode f90_node = new FullCPTNode((RandomVariable)f90, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f21_node = new FullCPTNode((RandomVariable)f21, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f90_node});
        new FullCPTNode((RandomVariable)f22, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f21_node});
        new FullCPTNode((RandomVariable)f23, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f24, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f25, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f26, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f27, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f28, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f92_node = new FullCPTNode((RandomVariable)f92, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f29, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)f92_node});
        FullCPTNode f98_node = new FullCPTNode((RandomVariable)f98, new double[]{0.95D, 0.05D, 0.5D, 0.5D}, new Node[]{(Node)fault_node});
        FullCPTNode f30_node = new FullCPTNode((RandomVariable)f30, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f98_node});
        FullCPTNode f31_node = new FullCPTNode((RandomVariable)f31, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f20_node, (Node)f41_node, (Node)f44_node});
        new FullCPTNode((RandomVariable)f32, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f56_node});
        new FullCPTNode((RandomVariable)f33, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f34, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f35, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f36, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f37, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f84_node = new FullCPTNode((RandomVariable)f84, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f20_node, (Node)f41_node});
        FullCPTNode f96_node = new FullCPTNode((RandomVariable)f96, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f41_node, (Node)f84_node});
        new FullCPTNode((RandomVariable)f38, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f41_node, (Node)f96_node});
        new FullCPTNode((RandomVariable)f39, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D}, new Node[]{(Node)fault_node, (Node)f96_node, (Node)f84_node, (Node)f41_node});
        new FullCPTNode((RandomVariable)f40, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f41_node, (Node)f96_node});
        new FullCPTNode((RandomVariable)f42, new double[]{0.95D, 0.05D, 0.5D, 0.5D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f43, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f45, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f46, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f42, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f44_node});
        FullCPTNode f85_node = new FullCPTNode((RandomVariable)f85, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f20_node, (Node)f44_node});
        new FullCPTNode((RandomVariable)f48, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f44_node, (Node)f85_node});
        new FullCPTNode((RandomVariable)f49, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f44_node});
        new FullCPTNode((RandomVariable)f50, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f44_node});
        new FullCPTNode((RandomVariable)f51, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f83_node = new FullCPTNode((RandomVariable)f83, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f41_node, (Node)f84_node});
        new FullCPTNode((RandomVariable)f54, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f83_node});
        new FullCPTNode((RandomVariable)f57, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f58, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f59, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f60, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f61_node = new FullCPTNode((RandomVariable)f54, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f53_node});
        new FullCPTNode((RandomVariable)f62, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f61_node});
        new FullCPTNode((RandomVariable)f63, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f64, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f65, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f66, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f61_node});
        new FullCPTNode((RandomVariable)f67, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f68, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f69, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f72_node = new FullCPTNode((RandomVariable)f72, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        FullCPTNode f86_node = new FullCPTNode((RandomVariable)f86, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)f20_node, (Node)f85_node, (Node)f84_node, (Node)f72_node});
        new FullCPTNode((RandomVariable)f70, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f72_node, (Node)f86_node});
        new FullCPTNode((RandomVariable)f71, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f72_node});
        new FullCPTNode((RandomVariable)f73, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f74, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f30_node, (Node)f98_node});
        new FullCPTNode((RandomVariable)f75, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f76, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f77, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f79, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f80, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f74, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f72_node, (Node)f86_node});
        FullCPTNode f82_node = new FullCPTNode((RandomVariable)f82, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f44_node, (Node)f85_node});
        FullCPTNode f87_node = new FullCPTNode((RandomVariable)f87, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f31_node, (Node)f41_node});
        FullCPTNode f88_node = new FullCPTNode((RandomVariable)f88, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f31_node, (Node)f44_node});
        new FullCPTNode((RandomVariable)f89, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.97D, 0.03D, 0.31D, 0.69D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D, 0.31D, 0.69D, 0.97D, 0.03D}, new Node[]{(Node)fault_node, (Node)f88_node, (Node)f87_node, (Node)f31_node, (Node)f72_node});
        new FullCPTNode((RandomVariable)f91, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f93, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.75D, 0.25D, 0.63D, 0.37D, 0.75D, 0.25D, 0.63D, 0.37D, 0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node, (Node)f83_node, (Node)f82_node});
        new FullCPTNode((RandomVariable)f94, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.75D, 0.25D, 0.63D, 0.37D, 0.75D, 0.25D, 0.63D, 0.37D, 0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node, (Node)f41_node, (Node)f96_node});
        new FullCPTNode((RandomVariable)f95, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node, (Node)f72_node});
        new FullCPTNode((RandomVariable)f99, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node, (Node)f90_node});
        new FullCPTNode((RandomVariable)f100, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node, (Node)f4_node});
        FullCPTNode f105_node = new FullCPTNode((RandomVariable)f105, new double[]{0.95D, 0.05D, 0.5D, 0.5D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f101, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node, (Node)f105_node});
        new FullCPTNode((RandomVariable)f102, new double[]{0.95D, 0.05D, 0.5D, 0.5D, 0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node, (Node)f105_node});
        new FullCPTNode((RandomVariable)f103, new double[]{0.95D, 0.05D, 0.5D, 0.5D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f104, new double[]{0.95D, 0.05D, 0.5D, 0.5D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f106, new double[]{0.95D, 0.05D, 0.5D, 0.5D}, new Node[]{(Node)fault_node});
        new FullCPTNode((RandomVariable)f107, new double[]{0.97D, 0.03D, 0.31D, 0.69D, 0.75D, 0.25D, 0.63D, 0.37D, 0.75D, 0.25D, 0.63D, 0.37D, 0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node, (Node)f41_node, (Node)f44_node});
        new FullCPTNode((RandomVariable)f108, new double[]{0.75D, 0.25D, 0.63D, 0.37D}, new Node[]{(Node)fault_node});
        return (BayesianNetwork)(new BayesNet(new Node[]{(Node)fault_node}));
    }

    private CustomBayesNetFactory() {
    }

    static {
        CustomBayesNetFactory var0 = new CustomBayesNetFactory();
        INSTANCE = var0;
    }
}
